export const sampleCompanyData = [
	{
		id: 1,
		company: "Tech Innovators Inc.",
		country: "USA",
		state: "California",
		city: "San Francisco",
		street: "123 Tech Lane",
		zipcode: "94107",
		email: "info@techinnovators.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 2,
		company: "Global Solutions Ltd.",
		country: "UK",
		state: "England",
		city: "London",
		street: "456 Global St.",
		zipcode: "EC1A 1BB",
		email: "contact@globalsolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 3,
		company: "Creative Minds LLC",
		country: "USA",
		state: "New York",
		city: "New York",
		street: "789 Creative Ave",
		zipcode: "10001",
		email: "hello@creativeminds.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 4,
		company: "Future Enterprises",
		country: "Canada",
		state: "Ontario",
		city: "Toronto",
		street: "101 Future Blvd",
		zipcode: "M5H 2N2",
		email: "info@futureenterprises.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 5,
		company: "Pioneer Technologies",
		country: "USA",
		state: "Texas",
		city: "Austin",
		street: "202 Pioneer Way",
		zipcode: "73301",
		email: "support@pioneertechnologies.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 6,
		company: "Visionary Ventures",
		country: "Australia",
		state: "New South Wales",
		city: "Sydney",
		street: "303 Visionary Rd",
		zipcode: "2000",
		email: "contact@visionaryventures.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 7,
		company: "NextGen Solutions",
		country: "Germany",
		state: "Bavaria",
		city: "Munich",
		street: "404 NextGen St.",
		zipcode: "80331",
		email: "info@nextgensolutions.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 8,
		company: "Elite Software",
		country: "USA",
		state: "Washington",
		city: "Seattle",
		street: "505 Elite Ave",
		zipcode: "98101",
		email: "support@elitesoftware.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 9,
		company: "Dynamic Systems",
		country: "India",
		state: "Karnataka",
		city: "Bangalore",
		street: "606 Dynamic Blvd",
		zipcode: "560001",
		email: "info@dynamicsystems.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 10,
		company: "Prime Innovations",
		country: "USA",
		state: "Florida",
		city: "Miami",
		street: "707 Prime St.",
		zipcode: "33101",
		email: "contact@primeinnovations.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 11,
		company: "Synergy Corp.",
		country: "USA",
		state: "Illinois",
		city: "Chicago",
		street: "808 Synergy Ave",
		zipcode: "60601",
		email: "info@synergycorp.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 12,
		company: "Quantum Tech",
		country: "Japan",
		state: "Tokyo",
		city: "Tokyo",
		street: "909 Quantum Blvd",
		zipcode: "100-0001",
		email: "support@quantumtech.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 13,
		company: "Infinity Labs",
		country: "USA",
		state: "Massachusetts",
		city: "Boston",
		street: "1010 Infinity St.",
		zipcode: "02108",
		email: "info@infinitylabs.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 14,
		company: "Epic Enterprises",
		country: "France",
		state: "Île-de-France",
		city: "Paris",
		street: "1111 Epic Ave",
		zipcode: "75001",
		email: "contact@epicenterprises.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 15,
		company: "Vertex Solutions",
		country: "USA",
		state: "Colorado",
		city: "Denver",
		street: "1212 Vertex Blvd",
		zipcode: "80201",
		email: "info@vertexsolutions.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 16,
		company: "Nexus Industries",
		country: "USA",
		state: "Georgia",
		city: "Atlanta",
		street: "1313 Nexus St.",
		zipcode: "30301",
		email: "support@nexusindustries.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 17,
		company: "Apex Innovations",
		country: "USA",
		state: "Nevada",
		city: "Las Vegas",
		street: "1414 Apex Ave",
		zipcode: "89101",
		email: "info@apexinnovations.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 18,
		company: "Fusion Technologies",
		country: "USA",
		state: "Arizona",
		city: "Phoenix",
		street: "1515 Fusion Blvd",
		zipcode: "85001",
		email: "contact@fusiontechnologies.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 19,
		company: "Summit Solutions",
		country: "USA",
		state: "Oregon",
		city: "Portland",
		street: "1616 Summit St.",
		zipcode: "97201",
		email: "info@summitsolutions.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 20,
		company: "Zenith Enterprises",
		country: "USA",
		state: "Utah",
		city: "Salt Lake City",
		street: "1717 Zenith Ave",
		zipcode: "84101",
		email: "support@zenithenterprises.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 21,
		company: "Alpha Technologies",
		country: "USA",
		state: "California",
		city: "Los Angeles",
		street: "1818 Alpha Blvd",
		zipcode: "90001",
		email: "info@alphatechnologies.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 22,
		company: "Beta Solutions",
		country: "USA",
		state: "New York",
		city: "Buffalo",
		street: "1919 Beta St.",
		zipcode: "14201",
		email: "contact@betasolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 23,
		company: "Gamma Enterprises",
		country: "USA",
		state: "Illinois",
		city: "Springfield",
		street: "2020 Gamma Ave",
		zipcode: "62701",
		email: "info@gammaenterprises.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 24,
		company: "Delta Corp.",
		country: "USA",
		state: "Texas",
		city: "Houston",
		street: "2121 Delta Blvd",
		zipcode: "77001",
		email: "support@deltacorp.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 25,
		company: "Epsilon Innovations",
		country: "USA",
		state: "Florida",
		city: "Orlando",
		street: "2222 Epsilon St.",
		zipcode: "32801",
		email: "info@epsiloninnovations.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 26,
		company: "Zeta Solutions",
		country: "USA",
		state: "Ohio",
		city: "Cleveland",
		street: "2323 Zeta Ave",
		zipcode: "44101",
		email: "contact@zetasolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 27,
		company: "Eta Enterprises",
		country: "USA",
		state: "Michigan",
		city: "Detroit",
		street: "2424 Eta Blvd",
		zipcode: "48201",
		email: "info@etaenterprises.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 28,
		company: "Theta Corp.",
		country: "USA",
		state: "Pennsylvania",
		city: "Philadelphia",
		street: "2525 Theta St.",
		zipcode: "19101",
		email: "support@thetacorp.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 29,
		company: "Iota Innovations",
		country: "USA",
		state: "Georgia",
		city: "Savannah",
		street: "2626 Iota Ave",
		zipcode: "31401",
		email: "info@iotainnovations.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 30,
		company: "Kappa Solutions",
		country: "USA",
		state: "North Carolina",
		city: "Charlotte",
		street: "2727 Kappa Blvd",
		zipcode: "28201",
		email: "contact@kappasolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 31,
		company: "Lambda Enterprises",
		country: "USA",
		state: "Virginia",
		city: "Richmond",
		street: "2828 Lambda St.",
		zipcode: "23201",
		email: "info@lambdaenterprises.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 32,
		company: "Mu Corp.",
		country: "USA",
		state: "Tennessee",
		city: "Nashville",
		street: "2929 Mu Blvd",
		zipcode: "37201",
		email: "support@mucorp.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 33,
		company: "Nu Innovations",
		country: "USA",
		state: "Kentucky",
		city: "Louisville",
		street: "3030 Nu Ave",
		zipcode: "40201",
		email: "info@nuinnovations.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 34,
		company: "Xi Solutions",
		country: "USA",
		state: "Indiana",
		city: "Indianapolis",
		street: "3131 Xi St.",
		zipcode: "46201",
		email: "contact@xisolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 35,
		company: "Omicron Enterprises",
		country: "USA",
		state: "Missouri",
		city: "Kansas City",
		street: "3232 Omicron Blvd",
		zipcode: "64101",
		email: "info@omicronenterprises.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 36,
		company: "Pi Corp.",
		country: "USA",
		state: "Wisconsin",
		city: "Milwaukee",
		street: "3333 Pi Ave",
		zipcode: "53201",
		email: "info@picorp.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 37,
		company: "Rho Technologies",
		country: "USA",
		state: "Ohio",
		city: "Cleveland",
		street: "3434 Rho St.",
		zipcode: "44101",
		email: "contact@rhotek.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 38,
		company: "Sigma Solutions",
		country: "USA",
		state: "Michigan",
		city: "Detroit",
		street: "3535 Sigma Blvd",
		zipcode: "48201",
		email: "info@sigmasolutions.com",
		headquarter: "No",
		active: true,
	},
	{
		id: 39,
		company: "Tau Enterprises",
		country: "USA",
		state: "Minnesota",
		city: "Minneapolis",
		street: "3636 Tau Ave",
		zipcode: "55401",
		email: "support@tauenterprises.com",
		headquarter: "Yes",
		active: true,
	},
	{
		id: 40,
		company: "Upsilon Innovations",
		country: "USA",
		state: "Tennessee",
		city: "Nashville",
		street: "3737 Upsilon St.",
		zipcode: "37201",
		email: "contact@upsiloninnovations.com",
		headquarter: "No",
		active: true,
	},
];

export const sampleSiteData = [
	{
		id: 1,
		site: "Main Office",
		address: "123 Corporate Blvd, Suite 100",
		city: "New York",
		state: "NY",
		zipcode: "10001",
		active: true,
	},
	{
		id: 2,
		site: "Branch Office",
		address: "456 Business Rd, Suite 200",
		city: "Los Angeles",
		state: "CA",
		zipcode: "90001",
		active: false,
	},
	{
		id: 3,
		site: "Remote Office",
		address: "789 Industrial Ave, Suite 300",
		city: "Chicago",
		state: "IL",
		zipcode: "60601",
		active: true,
	},
	{
		id: 4,
		site: "East Coast Office",
		address: "101 East St, Suite 400",
		city: "Boston",
		state: "MA",
		zipcode: "02101",
		active: true,
	},
	{
		id: 5,
		site: "West Coast Office",
		address: "202 West St, Suite 500",
		city: "San Francisco",
		state: "CA",
		zipcode: "94101",
		active: false,
	},
	{
		id: 6,
		site: "Southern Office",
		address: "303 South St, Suite 600",
		city: "Houston",
		state: "TX",
		zipcode: "77001",
		active: true,
	},
	{
		id: 7,
		site: "Northern Office",
		address: "404 North St, Suite 700",
		city: "Minneapolis",
		state: "MN",
		zipcode: "55401",
		active: true,
	},
	{
		id: 8,
		site: "Central Office",
		address: "505 Central Ave, Suite 800",
		city: "Kansas City",
		state: "MO",
		zipcode: "64101",
		active: false,
	},
	{
		id: 9,
		site: "Midwest Office",
		address: "606 Midwest Blvd, Suite 900",
		city: "Columbus",
		state: "OH",
		zipcode: "43201",
		active: true,
	},
	{
		id: 10,
		site: "Southeast Office",
		address: "707 Southeast St, Suite 1000",
		city: "Atlanta",
		state: "GA",
		zipcode: "30301",
		active: true,
	},
	{
		id: 11,
		site: "Northeast Office",
		address: "808 Northeast Blvd, Suite 1100",
		city: "Philadelphia",
		state: "PA",
		zipcode: "19101",
		active: false,
	},
	{
		id: 12,
		site: "Southwest Office",
		address: "909 Southwest St, Suite 1200",
		city: "Phoenix",
		state: "AZ",
		zipcode: "85001",
		active: true,
	},
	{
		id: 13,
		site: "Northwest Office",
		address: "1010 Northwest Blvd, Suite 1300",
		city: "Seattle",
		state: "WA",
		zipcode: "98101",
		active: true,
	},
	{
		id: 14,
		site: "Mountain Office",
		address: "1111 Mountain Rd, Suite 1400",
		city: "Denver",
		state: "CO",
		zipcode: "80201",
		active: false,
	},
	{
		id: 15,
		site: "Pacific Office",
		address: "1212 Pacific Blvd, Suite 1500",
		city: "San Diego",
		state: "CA",
		zipcode: "92101",
		active: true,
	},
	{
		id: 16,
		site: "Atlantic Office",
		address: "1313 Atlantic Ave, Suite 1600",
		city: "Miami",
		state: "FL",
		zipcode: "33101",
		active: true,
	},
	{
		id: 17,
		site: "Gulf Coast Office",
		address: "1414 Gulf Blvd, Suite 1700",
		city: "New Orleans",
		state: "LA",
		zipcode: "70101",
		active: false,
	},
	{
		id: 18,
		site: "Great Lakes Office",
		address: "1515 Great Lakes St, Suite 1800",
		city: "Cleveland",
		state: "OH",
		zipcode: "44101",
		active: true,
	},
	{
		id: 19,
		site: "Plains Office",
		address: "1616 Plains Rd, Suite 1900",
		city: "Omaha",
		state: "NE",
		zipcode: "68101",
		active: true,
	},
	{
		id: 20,
		site: "Desert Office",
		address: "1717 Desert Blvd, Suite 2000",
		city: "Las Vegas",
		state: "NV",
		zipcode: "89101",
		active: false,
	},
	{
		id: 21,
		site: "Valley Office",
		address: "1818 Valley Rd, Suite 2100",
		city: "Salt Lake City",
		state: "UT",
		zipcode: "84101",
		active: true,
	},
	{
		id: 22,
		site: "Bay Area Office",
		address: "1919 Bay St, Suite 2200",
		city: "Oakland",
		state: "CA",
		zipcode: "94601",
		active: true,
	},
	{
		id: 23,
		site: "Capital Office",
		address: "2020 Capital Blvd, Suite 2300",
		city: "Washington",
		state: "DC",
		zipcode: "20001",
		active: false,
	},
	{
		id: 24,
		site: "Metro Office",
		address: "2121 Metro Rd, Suite 2400",
		city: "Detroit",
		state: "MI",
		zipcode: "48201",
		active: true,
	},
	{
		id: 25,
		site: "Urban Office",
		address: "2222 Urban Blvd, Suite 2500",
		city: "Baltimore",
		state: "MD",
		zipcode: "21201",
		active: true,
	},
	{
		id: 26,
		site: "Suburban Office",
		address: "2323 Suburban Rd, Suite 2600",
		city: "Charlotte",
		state: "NC",
		zipcode: "28201",
		active: false,
	},
	{
		id: 27,
		site: "Rural Office",
		address: "2424 Rural Blvd, Suite 2700",
		city: "Des Moines",
		state: "IA",
		zipcode: "50301",
		active: true,
	},
	{
		id: 28,
		site: "Coastal Office",
		address: "2525 Coastal Rd, Suite 2800",
		city: "Virginia Beach",
		state: "VA",
		zipcode: "23401",
		active: true,
	},
	{
		id: 29,
		site: "Inland Office",
		address: "2626 Inland Blvd, Suite 2900",
		city: "Raleigh",
		state: "NC",
		zipcode: "27601",
		active: false,
	},
	{
		id: 30,
		site: "Lakeside Office",
		address: "2727 Lakeside Rd, Suite 3000",
		city: "Madison",
		state: "WI",
		zipcode: "53701",
		active: true,
	},
	{
		id: 31,
		site: "Riverfront Office",
		address: "2828 Riverfront Blvd, Suite 3100",
		city: "St. Louis",
		state: "MO",
		zipcode: "63101",
		active: true,
	},
	{
		id: 32,
		site: "Hilltop Office",
		address: "2929 Hilltop Rd, Suite 3200",
		city: "Pittsburgh",
		state: "PA",
		zipcode: "15201",
		active: false,
	},
	{
		id: 33,
		site: "Parkside Office",
		address: "3030 Parkside Blvd, Suite 3300",
		city: "Orlando",
		state: "FL",
		zipcode: "32801",
		active: true,
	},
	{
		id: 34,
		site: "Countryside Office",
		address: "3131 Countryside Rd, Suite 3400",
		city: "Nashville",
		state: "TN",
		zipcode: "37201",
		active: true,
	},
	{
		id: 35,
		site: "Forest Office",
		address: "3232 Forest Blvd, Suite 3500",
		city: "Portland",
		state: "OR",
		zipcode: "97201",
		active: false,
	},
	{
		id: 36,
		site: "Mountain View Office",
		address: "3333 Mountain View Rd, Suite 3600",
		city: "Boise",
		state: "ID",
		zipcode: "83701",
		active: true,
	},
	{
		id: 37,
		site: "Lakeshore Office",
		address: "3434 Lakeshore Blvd, Suite 3700",
		city: "Buffalo",
		state: "NY",
		zipcode: "14201",
		active: true,
	},
	{
		id: 38,
		site: "Seaside Office",
		address: "3535 Seaside Rd, Suite 3800",
		city: "Charleston",
		state: "SC",
		zipcode: "29401",
		active: false,
	},
	{
		id: 39,
		site: "Harbor Office",
		address: "3636 Harbor Blvd, Suite 3900",
		city: "Norfolk",
		state: "VA",
		zipcode: "23501",
		active: true,
	},
	{
		id: 40,
		site: "Island Office",
		address: "3737 Island Rd, Suite 4000",
		city: "Honolulu",
		state: "HI",
		zipcode: "96801",
		active: true,
	},
	{
		id: 41,
		site: "Peninsula Office",
		address: "3838 Peninsula Blvd, Suite 4100",
		city: "San Mateo",
		state: "CA",
		zipcode: "94401",
		active: false,
	},
	{
		id: 42,
		site: "Canyon Office",
		address: "3939 Canyon Rd, Suite 4200",
		city: "Tucson",
		state: "AZ",
		zipcode: "85701",
		active: true,
	},
	{
		id: 43,
		site: "Prairie Office",
		address: "4040 Prairie Blvd, Suite 4300",
		city: "Fargo",
		state: "ND",
		zipcode: "58101",
		active: true,
	},
	{
		id: 44,
		site: "Plateau Office",
		address: "4141 Plateau Rd, Suite 4400",
		city: "Albuquerque",
		state: "NM",
		zipcode: "87101",
		active: false,
	},
	{
		id: 45,
		site: "Foothills Office",
		address: "4242 Foothills Blvd, Suite 4500",
		city: "Boulder",
		state: "CO",
		zipcode: "80301",
		active: true,
	},
	{
		id: 46,
		site: "Bluffs Office",
		address: "4343 Bluffs Rd, Suite 4600",
		city: "Sioux Falls",
		state: "SD",
		zipcode: "57101",
		active: true,
	},
	{
		id: 47,
		site: "Dunes Office",
		address: "4444 Dunes Blvd, Suite 4700",
		city: "Mobile",
		state: "AL",
		zipcode: "36601",
		active: false,
	},
	{
		id: 48,
		site: "Glades Office",
		address: "4545 Glades Rd, Suite 4800",
		city: "Fort Lauderdale",
		state: "FL",
		zipcode: "33301",
		active: true,
	},
	{
		id: 49,
		site: "Savannah Office",
		address: "4646 Savannah Blvd, Suite 4900",
		city: "Savannah",
		state: "GA",
		zipcode: "31401",
		active: true,
	},
	{
		id: 50,
		site: "Delta Office",
		address: "4747 Delta Rd, Suite 5000",
		city: "Memphis",
		state: "TN",
		zipcode: "38101",
		active: false,
	},
];

export const sampleWarehouseData = [
	{
		id: 1,
		warehouse: "Central Warehouse",
		address: "123 Distribution Rd",
		city: "Chicago",
		state: "IL",
		zipcode: "60601",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 2,
		warehouse: "East Warehouse",
		address: "456 Logistics Ave",
		city: "New York",
		state: "NY",
		zipcode: "10001",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 3,
		warehouse: "West Warehouse",
		address: "789 Supply St",
		city: "Los Angeles",
		state: "CA",
		zipcode: "90001",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 4,
		warehouse: "North Warehouse",
		address: "101 Storage Blvd",
		city: "Minneapolis",
		state: "MN",
		zipcode: "55401",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 5,
		warehouse: "South Warehouse",
		address: "202 Depot Rd",
		city: "Houston",
		state: "TX",
		zipcode: "77001",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 6,
		warehouse: "Midwest Warehouse",
		address: "303 Freight Ave",
		city: "Columbus",
		state: "OH",
		zipcode: "43201",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 7,
		warehouse: "Southeast Warehouse",
		address: "404 Cargo St",
		city: "Atlanta",
		state: "GA",
		zipcode: "30301",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 8,
		warehouse: "Northeast Warehouse",
		address: "505 Distribution Blvd",
		city: "Boston",
		state: "MA",
		zipcode: "02101",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 9,
		warehouse: "Southwest Warehouse",
		address: "606 Warehouse Rd",
		city: "Phoenix",
		state: "AZ",
		zipcode: "85001",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 10,
		warehouse: "Northwest Warehouse",
		address: "707 Storage Ave",
		city: "Seattle",
		state: "WA",
		zipcode: "98101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 11,
		warehouse: "Mountain Warehouse",
		address: "808 Logistics Blvd",
		city: "Denver",
		state: "CO",
		zipcode: "80201",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 12,
		warehouse: "Pacific Warehouse",
		address: "909 Supply Rd",
		city: "San Francisco",
		state: "CA",
		zipcode: "94101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 13,
		warehouse: "Atlantic Warehouse",
		address: "1010 Depot Ave",
		city: "Miami",
		state: "FL",
		zipcode: "33101",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 14,
		warehouse: "Gulf Warehouse",
		address: "1111 Freight Blvd",
		city: "New Orleans",
		state: "LA",
		zipcode: "70101",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 15,
		warehouse: "Great Lakes Warehouse",
		address: "1212 Cargo Rd",
		city: "Cleveland",
		state: "OH",
		zipcode: "44101",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 16,
		warehouse: "Plains Warehouse",
		address: "1313 Distribution Ave",
		city: "Omaha",
		state: "NE",
		zipcode: "68101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 17,
		warehouse: "Desert Warehouse",
		address: "1414 Warehouse Blvd",
		city: "Las Vegas",
		state: "NV",
		zipcode: "89101",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 18,
		warehouse: "Valley Warehouse",
		address: "1515 Storage Rd",
		city: "Salt Lake City",
		state: "UT",
		zipcode: "84101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 19,
		warehouse: "Bay Area Warehouse",
		address: "1616 Logistics Ave",
		city: "Oakland",
		state: "CA",
		zipcode: "94601",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 20,
		warehouse: "Capital Warehouse",
		address: "1717 Supply Blvd",
		city: "Washington",
		state: "DC",
		zipcode: "20001",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 21,
		warehouse: "Metro Warehouse",
		address: "1818 Depot Rd",
		city: "Detroit",
		state: "MI",
		zipcode: "48201",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 22,
		warehouse: "Urban Warehouse",
		address: "1919 Freight Ave",
		city: "Baltimore",
		state: "MD",
		zipcode: "21201",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 23,
		warehouse: "Suburban Warehouse",
		address: "2020 Cargo Blvd",
		city: "Charlotte",
		state: "NC",
		zipcode: "28201",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 24,
		warehouse: "Rural Warehouse",
		address: "2121 Distribution Rd",
		city: "Des Moines",
		state: "IA",
		zipcode: "50301",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 25,
		warehouse: "Coastal Warehouse",
		address: "2222 Warehouse Ave",
		city: "Virginia Beach",
		state: "VA",
		zipcode: "23401",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 26,
		warehouse: "Inland Warehouse",
		address: "2323 Storage Blvd",
		city: "Raleigh",
		state: "NC",
		zipcode: "27601",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 27,
		warehouse: "Lakeside Warehouse",
		address: "2424 Logistics Rd",
		city: "Madison",
		state: "WI",
		zipcode: "53701",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 28,
		warehouse: "Riverfront Warehouse",
		address: "2525 Supply Ave",
		city: "St. Louis",
		state: "MO",
		zipcode: "63101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 29,
		warehouse: "Hilltop Warehouse",
		address: "2626 Depot Blvd",
		city: "Pittsburgh",
		state: "PA",
		zipcode: "15201",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 30,
		warehouse: "Parkside Warehouse",
		address: "2727 Freight Rd",
		city: "Orlando",
		state: "FL",
		zipcode: "32801",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 31,
		warehouse: "Countryside Warehouse",
		address: "2828 Cargo Ave",
		city: "Nashville",
		state: "TN",
		zipcode: "37201",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 32,
		warehouse: "Forest Warehouse",
		address: "2929 Distribution Blvd",
		city: "Portland",
		state: "OR",
		zipcode: "97201",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 33,
		warehouse: "Mountain View Warehouse",
		address: "3030 Warehouse Rd",
		city: "Boise",
		state: "ID",
		zipcode: "83701",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 34,
		warehouse: "Lakeshore Warehouse",
		address: "3131 Storage Ave",
		city: "Buffalo",
		state: "NY",
		zipcode: "14201",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 35,
		warehouse: "Seaside Warehouse",
		address: "3232 Logistics Blvd",
		city: "Charleston",
		state: "SC",
		zipcode: "29401",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 36,
		warehouse: "Harbor Warehouse",
		address: "3333 Supply Rd",
		city: "Norfolk",
		state: "VA",
		zipcode: "23501",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 37,
		warehouse: "Island Warehouse",
		address: "3434 Depot Ave",
		city: "Honolulu",
		state: "HI",
		zipcode: "96801",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 38,
		warehouse: "Peninsula Warehouse",
		address: "3535 Freight Blvd",
		city: "San Mateo",
		state: "CA",
		zipcode: "94401",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 39,
		warehouse: "Canyon Warehouse",
		address: "3636 Cargo Rd",
		city: "Tucson",
		state: "AZ",
		zipcode: "85701",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 40,
		warehouse: "Prairie Warehouse",
		address: "3737 Distribution Ave",
		city: "Fargo",
		state: "ND",
		zipcode: "58101",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 41,
		warehouse: "Plateau Warehouse",
		address: "3838 Warehouse Blvd",
		city: "Albuquerque",
		state: "NM",
		zipcode: "87101",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 42,
		warehouse: "Foothills Warehouse",
		address: "3939 Storage Rd",
		city: "Boulder",
		state: "CO",
		zipcode: "80301",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 43,
		warehouse: "Highland Warehouse",
		address: "4040 Logistics Ave",
		city: "Asheville",
		state: "NC",
		zipcode: "28801",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 44,
		warehouse: "Lowland Warehouse",
		address: "4141 Supply Blvd",
		city: "Baton Rouge",
		state: "LA",
		zipcode: "70801",
		sameAsSite: "Yes",
		active: false,
	},
	{
		id: 45,
		warehouse: "Delta Warehouse",
		address: "4242 Depot Rd",
		city: "Memphis",
		state: "TN",
		zipcode: "38101",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 46,
		warehouse: "Savannah Warehouse",
		address: "4343 Freight Ave",
		city: "Savannah",
		state: "GA",
		zipcode: "31401",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 47,
		warehouse: "Everglades Warehouse",
		address: "4444 Cargo St",
		city: "Fort Lauderdale",
		state: "FL",
		zipcode: "33301",
		sameAsSite: "No",
		active: false,
	},
	{
		id: 48,
		warehouse: "Tundra Warehouse",
		address: "4545 Distribution Blvd",
		city: "Anchorage",
		state: "AK",
		zipcode: "99501",
		sameAsSite: "Yes",
		active: true,
	},
	{
		id: 49,
		warehouse: "Glacier Warehouse",
		address: "4646 Warehouse Rd",
		city: "Juneau",
		state: "AK",
		zipcode: "99801",
		sameAsSite: "No",
		active: true,
	},
	{
		id: 50,
		warehouse: "Rainforest Warehouse",
		address: "4747 Storage Ave",
		city: "Seattle",
		state: "WA",
		zipcode: "98101",
		sameAsSite: "Yes",
		active: false,
	},
];
